server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/libra
spring.datasource.username=postgres
spring.datasource.password=1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
