server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/libra
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  thymeleaf:
    cache: false

app:
  api:
    base-url: http://localhost:8080

